### ISSUE TITLE
Contribute @Export decorator and others

### ISSUE THREAD

**Issue by Paebbels** [mplanchard/pydecor#6]
According to the roadmap for [v1.2](https://pydecor.readthedocs.io/en/latest/#id1), you would like to integrate an `@Export` decorator. I have such an implementation and I'm looking for a package to host that decorator.

I could create my own package on PyPI, but all good names are already used and your `pydecor` looks like a very good collection of useful decorators.

- Against what branch should I create the PR?
- Any rules to follow?
- I'm ok with MIT license. Anything to sign (Contributors License Agreement - CLA or similar?)

**Comment by mplanchard** [comment]
@Paebbels this sounds great. Sorry for the delay. The end of Q4 is a very busy time for me every year, and my OSS responsibilities always fall by the wayside.

I haven't updated this project in a while, and there are some changes I would like to make to the existing API and to the roadmap. Now that Python 2 is EoL'ed, we can just use type annotations rather than adding stubfiles, for example.

Adding a `@export` decorator still seems like an excellent idea, and I'd be happy to pull in your contribution.

To contribute, just fork and open a PR against master. Once it gets merged, I'll bump the version and do a release on PyPI. The only hard rule is ensuring things are adequately tested! I've started using `black` in other projects for formatting, but I'll add that in here at some point down the road, so no need to worry about it yet. Regarding the license, there's nothing to sign and no complications!

**Comment by Paebbels** [comment]
I have no knowledge about pytest. What I can say is, this decorator is used in several of my projects.

I have already a fork of your repo. I'll create two PRs:
- one for the decorator, and
- one for Travis-CI

... or do you prefer switching directly to GitHub Actions (GHA)?

I have now a minimal flow for GHA, but I have more knowledge if it comes to Travis, GitLab, AppVeyor or similar. In contrast GitHub tries to over complicate CI configs ...

**Comment by mplanchard** [comment]
It's okay. If you open a PR w/the code and no tests, I can write some tests against the PR. 

I'm not a huge fan of Travis and am OK with moving towards GHA or another provider. I've been using Azure in my other projects ever since Travis fired all of their senior developers. I'm also OK with staying with Travis for the moment and just switching later.

**Comment by Paebbels** [comment]
Hmmm, unfortunately GitHub didn't close the matching issue when closing the PR.

I think we can close this, or do you like to collect further related work in here?

**Comment by mplanchard** [comment]
Resolved in #9
